



export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLE = 'GET_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_TAGS = 'GET_TAGS'
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const ERROR_HANDLE = 'ERROR_HANDLE'
export const RESET_ADD_MODAL_VISIBLE = 'RESET_ADD_MODAL_VISIBLE'



